spring:
  application:
    name: api-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/tasks}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

task:
  encryption:
    key: ${TASK_ENCRYPTION_KEY}

ai:
  service:
    url: ${AI_SERVICE_URL:http://ai-service:8001}
